### ISSUE TITLE
Improve-template-api

### ISSUE THREAD

**Issue by EsteveSegura** [keep-secrets/template-api#1]
In this API template we need to add all the basics we need to make it work. Lets make a list.

- Jest testing (max workers 1 and passing with no test)
- eslint
- structure folder (infra,domain... etc)
- minimal express config
- default helathcheck endpoint (we dont need to apply checks)
- graceful stopper (we dont need to stop anything at this point, but lets have this)
- Docker
- Docker-compose
- Mongo db handler
- package.json with minimal scripts (run, dev with nodemon, test)

**Comment by AlfonMnz** [comment]
I take it

**Comment by EsteveSegura** [comment]
All yours

**Comment by AlfonMnz** [comment]
<3
